---
- name: "oauth2_proxy | Include pre requisite tasks"
  ansible.builtin.import_tasks:
    file: "pre_requisite.yml"
- name: "oauth2_proxy | Include packages tasks"
  ansible.builtin.include_tasks:
    file: "packages.yml"
  when:
    - "hostvars[inventory_hostname]['oauth2_proxy'] is defined"
    - "hostvars[inventory_hostname]['oauth2_proxy'] != ''"
    - "hostvars[inventory_hostname]['oauth2_proxy'] |
       community.general.json_query(vars['oauth2p_install_package']) is defined"
    - "hostvars[inventory_hostname]['oauth2_proxy'] |
       community.general.json_query(vars['oauth2p_install_package']) == 'true'"
  vars:
    oauth2p_install_package: "[] | map(&install_package || 'false', @) | [0]"
- name: "oauth2_proxy | Include deployment tasks"
  ansible.builtin.import_tasks:
    file: "deploy_oauth2_proxy.yml"
